services:
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
    restart: unless-stopped
    expose:
      - "9000"
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html
    environment:
      SQL_DATABASE: ${DB_NAME}
      SQL_USER: ${DB_USER}
      SQL_PASSWORD: ${DB_PW}
      WP_URL: https://lferro.42.fr
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
      args:
        DOMAIN: lferro.42.fr
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DOMAIN=lferro.42.fr

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
    restart: unless-stopped
    expose:
      - "3306"
    environment:
      SQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      SQL_DATABASE: ${DB_NAME}
      SQL_USER: ${DB_USER}
      SQL_PASSWORD: ${DB_PW}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_net

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lferro/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lferro/data/mariadb

networks:
  inception_net:
